### ISSUE TITLE
Updates usually fail if components change

### ISSUE THREAD

**Issue by kmdavis** [lemonmade/remote-ui#10]
I have a component that initially renders a spinner and then updates to render actual content.

Most of the time, it just fails and keeps on failing (it's trying to update once a second):
<img width="1886" alt="Screen Shot 2020-03-19 at 11 04 28 AM" src="https://user-images.githubusercontent.com/132806/77087735-76c62580-69d1-11ea-8d25-29e4db4e7336.png">

> Cannot destructure property 'props' of 'component' as it is undefined.

I traced this to: [receiver.ts#L95-L96](https://github.com/lemonmade/remote-ui/blob/master/packages/core/src/receiver.ts#L95-L96)
```ts
        const component = this.attached.get(id) as RemoteComponentSerialization;
        const {props: oldProps} = component;
```
`component` is undefined (I'm guessing because of the change from a spinner to a text component) and so, obviously, destructuring it fails. The rest of this block would also have issues due to an undefined component.

I'm attaching 2 more screenshots. In the first, you can see the previously `attached` LoadingIndicator component, and in the second, you can see the props for the new Banner component, with a different `id`:
<img width="457" alt="Screen Shot 2020-03-19 at 11 10 43 AM" src="https://user-images.githubusercontent.com/132806/77088469-8003c200-69d2-11ea-99f1-7e0313d7fcd7.png">
<img width="460" alt="Screen Shot 2020-03-19 at 11 10 53 AM" src="https://user-images.githubusercontent.com/132806/77088475-8134ef00-69d2-11ea-9adf-ab16fc50d711.png">

my GUESS is that there's a step (swapping out the components) that gets occasionally lost; btw, if this doesn't fail, it doesn't fail at all, it'll go for 10 minutes with updates every second without any errors, but if it fails, it fails immediately and continually.

**Comment by lemonmade** [comment]
Fixed by https://github.com/lemonmade/remote-ui/commit/1116e7581bc725c9286f0e6e1b101d8fbc184c97, we might need a proper queuing mechanism at some point before mount resolves, but for now I think it's fine to fire-and-forget.
