### ISSUE TITLE
Add example of how to expose functions / application state to worker

### ISSUE THREAD

**Issue by jaredpalmer** [lemonmade/remote-ui#26]
E.g. the currently logged-in user? Or an authenticated fetch?

**Comment by lemonmade** [comment]
Thanks, great suggestions. I basically used them directly in the bottom third of the [comprehensive guide](https://github.com/lemonmade/remote-ui/blob/master/documentation/comprehensive-example.md), which now covers this topic, and the Create React App demo, which I updated with these features in [this commit](https://github.com/lemonmade/remote-ui/commit/02e668c23a37a9f42cd16b5f152a8b87f80410b2).
