### ISSUE TITLE
More realistic example

### ISSUE THREAD

**Issue by jaredpalmer** [lemonmade/remote-ui#27]
I tried to make the example more real world locally and got a little stuck. 

In a full demo, would be at least 2 packages and the app
- widget-worker
- @company/widgets (public ui component types) 
- create-react-app (actual app, would contain app and implementation of public ui components).

I tried to use tsdx to build the worker and a local file server. I then tried passing createPlainWorker(localhost:5000/worker.js) but it didn’t work. I couldn’t figure out what/if I need to transpile the worker or wrap it with certain worker code or Babel plugins. 

In a real world product, you would likely want to have the following packages:
- create-company-widget (cli to bootstrap a new worker)
- @company/widget-scripts (bundle, test, locally serve the worker, perhaps have deploy command) 
- @company/widgets (ui types)

AFAIK tsdx can handle the worker bundling? However, i think it’s a good idea for us to one day show recipes for a create-company-widget as well as  @company/widget-scripts (even if these are just a tiny wrappers around microbundle or tsdx)

**Comment by lemonmade** [comment]
`createPlainWorker` is just a shortcut that comes "for free" with the rest of the library to let the example build a separate, plain JS file, compiled as a worker. If you have an existing asset/ dev server for the file you intend to load in the worker, you should be able to pass it directly (basically as [the example does here](https://github.com/lemonmade/remote-ui/blob/main/examples/create-react-app/src/index.tsx#L15)).

You shouldn’t need any special wrapper around the worker code. We do have a package for build/ dev we will have available in a few days, but it's basically [this package](https://yarnpkg.com/package/argogogo-run?files), and is mostly a wrapper around [this webpack config](https://cdn.jsdelivr.net/npm/argogogo-run@0.3.0/src/webpack-config.ts). The `@shopify/argo-webpack-hot-client` stuff isn't necessary, it's just an additional layer I added to get a Webpack-dev-middleware to send hot updates to the worker. It requires extra integration to teach the worker how to ask the main page to reload itself, though.

I did originally have it [building with rollup](https://cdn.jsdelivr.net/npm/argogogo-run@0.2.0/src/build.ts), but I could not for the life of me figure out some problems rollup had with `react-reconciler` imports, so I went back to the tool I know better. I imagine you'll be able to get it working fine, and unfortunately moving to Webpack added 300–400 bytes gzipped to the minimum size I was able to achieve for a "real" extension 🤷

**Comment by lemonmade** [comment]
Hey @jaredpalmer, just a heads up that this repo's new home is under the Shopify org: https://github.com/Shopify/remote-ui. That version contains the 1.0 release, and some extra utility packages. If you need some more help, feel free to open an issue there.
